export { PGDASService } from './pgdas.service.js'
export { DifalService } from './difal.service.js'
export { FatorRService } from './fator-r.service.js'
export { DeSTDAService } from './destda.service.js'
export { GNREService } from './gnre.service.js'
export { EFDReinfService } from './efdreinf.service.js'
export { MonitoramentoSNService } from './monitoramento-sn.service.js'
export { AlertasVencimentosService } from './alertas-vencimentos.service.js'
export { DCTFWebService } from './dctfweb.service.js'
export { ESocialService } from './esocial.service.js'
export { FGTSDigitalService } from './fgts-digital.service.js'
export { DMSService } from './dms.service.js'
export type { ResultadoDMS, MunicipioISS } from './dms.service.js'
export { DasnService } from './dasn.service.js'
export type { ResultadoDasn, ReceitaMensalDasn } from './dasn.service.js'
export { CalendarioLPLRService } from './calendario-lplr.service.js'
export { IrpjCsllLPService } from './irpj-csll-lp.service.js'
export type { ResultadoIrpjCsllLP } from './irpj-csll-lp.service.js'
export { PisCofinsLPService } from './pis-cofins-lp.service.js'
export type { ResultadoPisCofinsLP } from './pis-cofins-lp.service.js'
export { ECFService } from './ecf.service.js'
export type { ResultadoECF, TrimestralECF } from './ecf.service.js'
export { DCTFMensalService } from './dctf-mensal.service.js'
export type { ResultadoDCTFMensal, ItemDCTF } from './dctf-mensal.service.js'
export { SpedFiscalService } from './sped-fiscal.service.js'
export type { ResultadoSpedFiscal } from './sped-fiscal.service.js'
export { SpedContribuicoesService } from './sped-contribuicoes.service.js'
export type { ResultadoSpedContribuicoes } from './sped-contribuicoes.service.js'
export type {
  ResultadoPGDAS,
  ReceitaSegregada,
  ResultadoDifal,
  ResultadoFGTS,
  ResultadoGRRF,
} from './types.js'
